### ISSUE TITLE
[menu] Information Architecture

### ISSUE THREAD

**Issue by jonrz** [joomla/joomla-ux#18]
Reorganize the menu in a **logical** and **intuitive** way.

### Link: [Menu on an unordered list](https://drive.google.com/open?id=1qgGek1EbfoX-PqaSMO6i16SMZkX4waeA3qNBukoRblo)

Please check the current J4 (grab a nightly, do a git clone, or ask Tony Partridge on Glip for access to an existing install), and [this document](https://drive.google.com/open?id=1Z6wAhwW7RM_H5RX3Hg5_T0mpSXXdIL19eZH701R2r6k), for work already done in this regard.

We are looking for a third, and maybe fourth options for reorganizing the menu, as well as improving the flux menu proposal.
The focus is the new, unexperienced user, but without disregarding current users.
We will not dumb down or trim down the menu, nor go around changing many titles, since we need to make it work for almost everyone.

Reducing the number of top level menus is highly desirable, and so is avoiding solo top level menus (such as media manager or module manager).

I feel the flux menu comes close to a major reorganization with minimal name changing, so current users are preserved, and new users are favored. 

Refer to #4 for the list of sub-tasks for the menu overhaul.

**Comment by rgmears** [comment]
Could you please present the existing menu structure as an unordered nested list.

**Comment by jonrz** [comment]
As promised, the menu on an unordered list is there.

**Comment by rgmears** [comment]
So, how do we do edits?

**Comment by brianpeat** [comment]
I created a J4 install that I plan to use to mess with the custom admin menu system in order to mock up some ideas. My thought is to make a few users/menus so we can each toss around some ideas and then have a discussion on why we changed what we changed and see if we can come to some sort of solution we're all okay with. None of us will be completely happy, so we all have to be okay with possibly not getting everything we want in a menu. The bigger goal is to make it more approachable by new users but also not completely confusing to life long users. That's a big task so we have to really think it through.

Honestly I'd encourage going REALLY FAR out of the box at first to spark some discussion and make us really think about how Joomla works and how the menus are designed and then we can pull back and find a solid solution.

**Comment by rgmears** [comment]
I agree @brianpeat there is much to do. I just took a second look at the standard Admin section and it is confusing. Nothing like a challenge.

**Comment by jonrz** [comment]
Removed the name FLUX, because it's not that anymore.
The new name is Alternate 01. We should work on it, and if possible create an alternate 02 for comparison.

**Comment by jonrz** [comment]
Good progress today in the menu organization, result of a 2 hours hangouts brainstorm session.
Check the sheet "proposal 01" in [this document](https://docs.google.com/spreadsheets/d/1qgGek1EbfoX-PqaSMO6i16SMZkX4waeA3qNBukoRblo).

### if you want to make changes, duplicate the sheet
Then rename it and do your changes.
Everyone is welcome to either try their own or comment on current proposals.
If you add your name to the sheet you just cloned, no one should touch it.
After a sheet is marked "proposal X", it stays frozen, to be adjusted only in live brainstorm sessions.

**Comment by rgmears** [comment]
@jonrz I added my first draft -- RGMEARS 01 -- to the [document](https://docs.google.com/spreadsheets/d/1qgGek1EbfoX-PqaSMO6i16SMZkX4waeA3qNBukoRblo/edit#gid=767091223).

**Comment by jonrz** [comment]
This architecture is settled, for now...
I'm closing this issue, and we'll add architecture changes at the design phase.
